parameters:
  vmImageName: 'ubuntu-16.04'
  resourceGroupName: 'WebApiWithNetCoreArmTest'
  imageRepository: ''
  subscription: ''
  templateFile: ''
  parametersFile: ''

stages:
  - stage: create_azure_group_from_template
    displayName: Create Azure Group From Template
    jobs:
      - job: create_azure_group_from_template
        pool:
          vmImageName: ${{ parameters.vmImageName }}
        steps:
          - task: AzureCLI@1
            displayName: Create Azure Resource Group from template
            inputs:
              azureSubscription: ${{ parameters.subscription }}
              scriptLocation: 'inlineScript'
              inlineScript: az group deployment create -g ${{ parameters.resourceGroupName }} --template-file ${{ parameters.templateFile }}  --parameters ${{ parameters.parametersFile }}
#
#          - task: AzureCLI@1
#            displayName: Delete Azure Group
#            inputs:
#              azureSubscription: ${{ parameters.subscription }}
#              scriptLocation: 'inlineScript'
#              inlineScript: az group deployment delete -g ${{ parameters.resourceGroupName }}